[package]
name = "api"
version = "0.1.0"
authors = ["Guilherme775 <guilhermereis28122002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
serde = "*"
serde_json = "*"